general:
  ##Seconds in a cycle
  timer: 900
  ##Location of lobby
  lobby: 'null'
  
spawns:
  lms: 'null'
  koth: 'null'
  
hilltop: 'null'
hillticks: 20
hillradius: 8.0
kothscorelimit: 100